server:
  port: 18797
spring:
  application:
    name: gateway-simple
  cloud:
    gateway:
      discovery:
        locator:
          # \u8868\u660Egateway\u5F00\u542F\u670D\u52A1\u6CE8\u518C\u548C\u53D1\u73B0\u7684\u529F\u80FD\uFF0C\u5E76\u4E14spring cloud gateway\u81EA\u52A8\u6839\u636E\u670D\u52A1\u53D1\u73B0\u4E3A\u6BCF\u4E00\u4E2A\u670D\u52A1\u521B\u5EFA\u4E86\u4E00\u4E2Arouter\uFF0C\u8FD9\u4E2Arouter\u5C06\u4EE5\u670D\u52A1\u540D\u5F00\u5934\u7684\u8BF7\u6C42\u8DEF\u5F84\u8F6C\u53D1\u5230\u5BF9\u5E94\u7684\u670D\u52A1
          enabled: false
          # \u662F\u5C06\u8BF7\u6C42\u8DEF\u5F84\u4E0A\u7684\u670D\u52A1\u540D\u914D\u7F6E\u4E3A\u5C0F\u5199
          lower-case-service-id: true
      routes:
        - id: service-test
          uri: lb://SERVICE-TEST
          predicates:
            - Path=/api-a/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      #      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://localhost:18761/eureka/