server:
  port: 20002
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: centos001:8848
        namespace: dev
    gateway:
      routes:
        - id: auth-center
          uri: lb://auth-center-server/
          predicates:
            - Path=/auth/**,/gateway/auth/**
          filters:
            - RewritePath=(/gateway)?/auth/(?<path>.*), /$\{path}
        - id: social
          uri: lb://social/
          predicates:
            - Path=/social/**,/gateway/social/**
          filters:
            - RewritePath=(/gateway)?/social/(?<path>.*), /$\{path}
  security:
    oauth2:
      resourceserver:
        jwt:
          #配置RSA的公钥访问地址
          jwk-set-uri: http://localhost:20001/rsa/publicKey