spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/yywzt/SpringcloudConfig.git
          # 配置仓库路径
          search-paths: config
          # Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          username:
          password:
      # 配置仓库的分支
      label: master

    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: 139.199.179.164
    port: 5672
    username: guest
    password: guest

server:
  port: 8088

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://localhost:18761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh