spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/yywzt/SpringcloudConfig.git
          # 配置仓库路径
          search-paths: '{application}'
          # Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          username:
          password:
          # 本地缓存地址
#          basedir: ./configRepo/　　
          # 强制拉取配置，解决手动修改本地缓存配置后，无法拉取最新配置的问题
          force-pull: true
      # 配置仓库的分支
      label: master

    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: yyw-cloud

server:
  port: 8088

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://localhost:18761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh